# Generated by Django 4.2.7 on 2023-11-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_alter_car_options_alter_car_model_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
    ]
