# Generated by Django 4.2.7 on 2023-11-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('v', 'Vykdomas'), ('p', 'Pabaigtas'), ('n', 'Nepradėtas')], default='n', help_text='Statusas', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(help_text='Data: (YYYY-MM-DD) formatu', verbose_name='Data'),
        ),
    ]
