# Generated by Django 4.2.7 on 2023-11-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_order_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Due Back'),
        ),
    ]
