# Generated by Django 4.2.7 on 2023-11-16 09:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservice', '0010_orderreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderReview',
            new_name='CarReview',
        ),
    ]
