# Generated by Django 4.2.7 on 2023-11-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0012_profilis'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.car'),
        ),
        migrations.AlterField(
            model_name='profilis',
            name='nuotrauka',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
