# Generated by Django 4.2.7 on 2023-11-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0013_order_line_car_alter_profilis_nuotrauka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line',
            name='car',
        ),
    ]
