# Generated by Django 4.2.7 on 2023-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit_api', '0002_alter_albumreviewcomment_album_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumreview',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
